name: Группа "Группа"
highlighter: false
permalink: /:categories/:title/
destination: _site
pagination: 15
paginate_path: "/page:num"
encoding: utf-8
markdown: kramdown
kramdown:
 input: GFM
 hard_wrap: false
 extensions: ["strikethrough", "smart"]
